server:
   port: 9000
   
spring: 
   application:
      name: xk-config
   cloud:
      config:
         server:
            git:
               default-label: main
               uri: https://github.com/inori1122/config
               search-paths: /C89-S3-xk
               username:
               password:             
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka  