spring:
   application:
      name: xk-server

server:
   #Eureka 的默认端口是：8761
   port: 8000
   
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
